name: os_project
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_swiper : ^1.1.6
  font_awesome_flutter: ^8.11.0
  cached_network_image: ^2.5.0
  #wave: ^0.1.0
  wave:
   git:
    url: git://github.com/searchy2/wave.git
  google_fonts: ^1.1.0
  fl_chart: ^0.11.1
  charts_flutter: ^0.9.0
  splashscreen: ^1.2.0
  animated_text_kit: ^3.1.2
  auto_size_text: ^2.1.0
  lazy_data_table: ^0.2.1
  flutter_slidable: ^0.5.7
  liquid_pull_to_refresh: ^2.0.0
  timelines: ^0.0.2+1
  simple_animations: ^1.3.3
  fab_circular_menu: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
     - images/
     - images/Learn page images/


